title: Hotdog/Not hotdog
hero_image: images/banner.png
description: Use machine learning and a webcam to detect whether something is a hotdog or not
version: 4
listed: false
copyedit: false
last_tested: "2020-11-24"
steps:
  - title: Introduction
  - title: Create a machine learning model
  - title: Make an image detector
  - title: What next?
