title: ML-image-detection-starter
hero_image: images/banner.png
description: ML-image-detection-starter description
version: 4
listed: false
copyedit: false
last_tested: "2020-11-24"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
